---

- hosts: user
  become: true
  remote_user: user

  tasks:
     - name: Transfer the script
       copy: src=/home/user/del_cont_env.sh  dest=/home/user/ansible mode=0777

     - name: Execute the script
       shell:
         cmd: ./ansible/del_cont_env.sh 